general:
  # Options: debug, info, warning, error, critical
  log_level: "info"

discord:
  prefix: "?"
  token: "<BOT_TOKEN>"

plex:
  base_url: "<BASE_URL>"
  token: "<PLEX_TOKEN>"
  library_name: "<LIBRARY_NAME>"
